#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define IEEE802154_CONF_PANID 0x9846
#define IEEE802154_CONF_DEFAULT_CHANNEL 16

#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_APP LOG_LEVEL_INFO

#endif /* PROJECT_CONF_H_ */
